### ISSUE TITLE
Give more user control over fit guesses and fit limits

### ISSUE THREAD

**Issue by bdriehuys** [TeamXenonDuke/xenon-dynamic-spectroscopy-consortium#3]
The code works well for cases with good SNR and relatively normal RBC chemical shifts. However, some of our sicker patients have very low RBC signal, and low RBC shift. Obtaining good dynamic spectroscopy on these cases, often requires significant tinkering with the initial fit guesses as well as constraints on how far the algorithm can take certain parameters (like RBC shift). Currently these constraints and guesses are "under the hood." They need to be made more visible and easier for users to manipulate proactively when needed.

**Comment by davidmummy** [comment]
This is no longer required by the customer. Closing to be resurrected later if needed.
